### ISSUE TITLE
无法启动，没有sqlite_host

### ISSUE THREAD

**Issue by Agnes4m** [summerkirakira/CirnoBot#10]
python:3.8.10
以下是启动nb run的显示
```
 PS E:\text\texted bot\CirnoBot> nb run
05-03 22:16:16 [SUCCESS] nonebot | NoneBot is initializing...
05-03 22:16:16 [INFO] nonebot | Current Env: prod
05-03 22:16:16 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_apscheduler"
05-03 22:16:16 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_currency_conversion"
05-03 22:16:17 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_cute_message"
05-03 22:16:17 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_database_connector"
05-03 22:16:17 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_image_server"
05-03 22:16:17 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_kaiheila_check"
05-03 22:16:17 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_mc_info"
05-03 22:16:17 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_mc_fun"
05-03 22:16:18 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_mc_cocdicer"
05-03 22:16:18 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_message_recorder"
05-03 22:16:18 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_permission"
05-03 22:16:18 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_archive"
05-03 22:16:18 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_help"
05-03 22:16:19 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
05-03 22:16:20 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_what2eat"
05-03 22:16:20 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_tarot"
05-03 22:16:20 [SUCCESS] nonebot | Running NoneBot...
05-03 22:16:20 [INFO] uvicorn | Started server process [22696]
05-03 22:16:20 [INFO] uvicorn | Waiting for application startup.
d:\python3.8.10\lib\apscheduler\util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
05-03 22:16:20 [INFO] src | Scheduler Started
05-03 22:16:20 [ERROR] uvicorn | Traceback (most recent call last):
  File "d:\python3.8.10\lib\site-packages\starlette\routing.py", line 621, in lifespan
    async with self.lifespan_context(app):
  File "d:\python3.8.10\lib\site-packages\starlette\routing.py", line 518, in __aenter__
    await self._router.startup()
  File "d:\python3.8.10\lib\site-packages\starlette\routing.py", line 598, in startup
    await handler()
  File "E:\text\texted bot\CirnoBot\.\src\plugins\nonebot_plugin_database_connector\__init__.py", line 22, in connect_to_sqlite
    if config.sqlite_host:
AttributeError: 'Config' object has no attribute 'sqlite_host'

05-03 22:16:20 [ERROR] uvicorn | Application startup failed. Exiting.
```

**Comment by summerkirakira** [comment]
尝试使用Python 3.9？

**Comment by Agnes4m** [comment]
解决了，我先是下载了3.9.10python，正常启动了，然后换回3.8.10，也能正常启动了，不太清楚什么原因
