### ISSUE TITLE
在我运行机器人时遇到一些插件报错

### ISSUE THREAD

**Issue by QwindF** [summerkirakira/CirnoBot#19]
用的是pycharm

```
E:\IDEAyes\BOT\CirnoBot-master\venv\Scripts\python.exe E:\IDEAyes\BOT\CirnoBot-master\bot.py 
12-23 15:09:48 [SUCCESS] nonebot | NoneBot is initializing...
12-23 15:09:48 [INFO] nonebot | Current Env: prod
12-23 15:09:48 [ERROR] nonebot | Failed to import "src.plugins.nonebot_plugin_apscheduler"
Traceback (most recent call last):
  File "E:\IDEAyes\BOT\CirnoBot-master\bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "E:\IDEAyes\BOT\CirnoBot-master\cirno_util.py", line 45, in load_plugins
    nonebot.load_plugin(f"src.plugins.{plugin_name}")
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\IDEAyes\BOT\CirnoBot-master\src\plugins\nonebot_plugin_apscheduler\__init__.py", line 3, in <module>
    from nonebot import get_driver, export
ImportError: cannot import name 'export' from 'nonebot' (E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\__init__.py)
12-23 15:09:48 [ERROR] nonebot | Failed to import "src.plugins.nonebot_plugin_currency_conversion"
Traceback (most recent call last):
  File "E:\IDEAyes\BOT\CirnoBot-master\bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "E:\IDEAyes\BOT\CirnoBot-master\cirno_util.py", line 45, in load_plugins
    nonebot.load_plugin(f"src.plugins.{plugin_name}")
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\IDEAyes\BOT\CirnoBot-master\src\plugins\nonebot_plugin_currency_conversion\__init__.py", line 4, in <module>
    from nonebot.params import State
ImportError: cannot import name 'State' from 'nonebot.params' (E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\params.py)
12-23 15:09:48 [ERROR] nonebot | Failed to import "src.plugins.nonebot_plugin_cute_message"
Traceback (most recent call last):
  File "E:\IDEAyes\BOT\CirnoBot-master\bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "E:\IDEAyes\BOT\CirnoBot-master\cirno_util.py", line 45, in load_plugins
    nonebot.load_plugin(f"src.plugins.{plugin_name}")
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\IDEAyes\BOT\CirnoBot-master\src\plugins\nonebot_plugin_cute_message\__init__.py", line 2, in <module>
    from nonebot.params import State
ImportError: cannot import name 'State' from 'nonebot.params' (E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\params.py)
12-23 15:09:48 [ERROR] nonebot | Failed to import "src.plugins.nonebot_plugin_database_connector"
Traceback (most recent call last):
  File "E:\IDEAyes\BOT\CirnoBot-master\bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "E:\IDEAyes\BOT\CirnoBot-master\cirno_util.py", line 45, in load_plugins
    nonebot.load_plugin(f"src.plugins.{plugin_name}")
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\IDEAyes\BOT\CirnoBot-master\src\plugins\nonebot_plugin_database_connector\__init__.py", line 16, in <module>
    nonebot.export().sqlite_pool = sqlite_pool
AttributeError: module 'nonebot' has no attribute 'export'
12-23 15:09:48 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_image_server"
12-23 15:09:48 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_kaiheila_check"
12-23 15:09:48 [ERROR] nonebot | Failed to import "src.plugins.nonebot_plugin_mc_info"
Traceback (most recent call last):
  File "E:\IDEAyes\BOT\CirnoBot-master\bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "E:\IDEAyes\BOT\CirnoBot-master\cirno_util.py", line 45, in load_plugins
    nonebot.load_plugin(f"src.plugins.{plugin_name}")
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\IDEAyes\BOT\CirnoBot-master\src\plugins\nonebot_plugin_mc_info\__init__.py", line 11, in <module>
    export = nonebot.export()
AttributeError: module 'nonebot' has no attribute 'export'
12-23 15:09:48 [ERROR] nonebot | Failed to import "src.plugins.nonebot_plugin_mc_fun"
Traceback (most recent call last):
  File "E:\IDEAyes\BOT\CirnoBot-master\bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "E:\IDEAyes\BOT\CirnoBot-master\cirno_util.py", line 45, in load_plugins
    nonebot.load_plugin(f"src.plugins.{plugin_name}")
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\IDEAyes\BOT\CirnoBot-master\src\plugins\nonebot_plugin_mc_fun\__init__.py", line 9, in <module>
    from .listeners import *
  File "E:\IDEAyes\BOT\CirnoBot-master\src\plugins\nonebot_plugin_mc_fun\listeners.py", line 1, in <module>
    from ..nonebot_plugin_mc_info import MinecraftConnector
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "E:\IDEAyes\BOT\CirnoBot-master\src\plugins\nonebot_plugin_mc_info\__init__.py", line 11, in <module>
    export = nonebot.export()
AttributeError: module 'nonebot' has no attribute 'export'
12-23 15:09:48 [ERROR] nonebot | Failed to import "src.plugins.nonebot_plugin_mc_cocdicer"
Traceback (most recent call last):
  File "E:\IDEAyes\BOT\CirnoBot-master\bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "E:\IDEAyes\BOT\CirnoBot-master\cirno_util.py", line 45, in load_plugins
    nonebot.load_plugin(f"src.plugins.{plugin_name}")
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\IDEAyes\BOT\CirnoBot-master\src\plugins\nonebot_plugin_mc_cocdicer\__init__.py", line 1, in <module>
    from ..nonebot_plugin_mc_info import MinecraftConnector
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "E:\IDEAyes\BOT\CirnoBot-master\src\plugins\nonebot_plugin_mc_info\__init__.py", line 11, in <module>
    export = nonebot.export()
AttributeError: module 'nonebot' has no attribute 'export'
12-23 15:09:48 [ERROR] nonebot | Failed to import "src.plugins.nonebot_plugin_message_recorder"
Traceback (most recent call last):
  File "E:\IDEAyes\BOT\CirnoBot-master\bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "E:\IDEAyes\BOT\CirnoBot-master\cirno_util.py", line 45, in load_plugins
    nonebot.load_plugin(f"src.plugins.{plugin_name}")
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\IDEAyes\BOT\CirnoBot-master\src\plugins\nonebot_plugin_message_recorder\__init__.py", line 4, in <module>
    from .data_source import insert_new_row, current_folder, save_config_to_yaml, get_config
  File "E:\IDEAyes\BOT\CirnoBot-master\src\plugins\nonebot_plugin_message_recorder\data_source.py", line 7, in <module>
    export = nonebot.require("nonebot_plugin_database_connector")
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\load.py", line 165, in require
    plugin = load_plugin(name)
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\load.py", line 32, in load_plugin
    manager = PluginManager([module_path])
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 52, in __init__
    self.prepare_plugins()
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 94, in prepare_plugins
    raise RuntimeError(
RuntimeError: Plugin already exists: nonebot_plugin_database_connector! Check your plugin name
12-23 15:09:48 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_permission"
12-23 15:09:48 [ERROR] nonebot | Failed to import "src.plugins.nonebot_plugin_archive"
Traceback (most recent call last):
  File "E:\IDEAyes\BOT\CirnoBot-master\bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "E:\IDEAyes\BOT\CirnoBot-master\cirno_util.py", line 45, in load_plugins
    nonebot.load_plugin(f"src.plugins.{plugin_name}")
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\IDEAyes\BOT\CirnoBot-master\src\plugins\nonebot_plugin_archive\__init__.py", line 4, in <module>
    from nonebot.params import State
ImportError: cannot import name 'State' from 'nonebot.params' (E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\params.py)
12-23 15:09:48 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_help"
12-23 15:09:50 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
12-23 15:09:50 [ERROR] nonebot | Failed to import "nonebot_plugin_what2eat"
Traceback (most recent call last):
  File "E:\IDEAyes\BOT\CirnoBot-master\bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "E:\IDEAyes\BOT\CirnoBot-master\cirno_util.py", line 47, in load_plugins
    nonebot.load_plugin(plugin_name)
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot_plugin_what2eat\__init__.py", line 6, in <module>
    from .utils import eating_manager, Meals, GROUPS_ID
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot_plugin_what2eat\utils.py", line 15, in <module>
    _WHAT2EAT_PATH = nonebot.get_driver().config.what2eat_path
AttributeError: 'Config' object has no attribute 'what2eat_path'
12-23 15:09:50 [ERROR] nonebot | Failed to import "nonebot_plugin_tarot"
Traceback (most recent call last):
  File "E:\IDEAyes\BOT\CirnoBot-master\bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "E:\IDEAyes\BOT\CirnoBot-master\cirno_util.py", line 47, in load_plugins
    nonebot.load_plugin(plugin_name)
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot_plugin_tarot\__init__.py", line 5, in <module>
    from .data_source import Cards, meanings
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot_plugin_tarot\data_source.py", line 6, in <module>
    _TAROT_PATH = nonebot.get_driver().config.tarot_path
AttributeError: 'Config' object has no attribute 'tarot_path'
12-23 15:09:50 [ERROR] nonebot | Failed to import "src.plugins.nonebot_plugin_haruka_bot"
Traceback (most recent call last):
  File "E:\IDEAyes\BOT\CirnoBot-master\bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "E:\IDEAyes\BOT\CirnoBot-master\cirno_util.py", line 45, in load_plugins
    nonebot.load_plugin(f"src.plugins.{plugin_name}")
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\IDEAyes\BOT\CirnoBot-master\src\plugins\nonebot_plugin_haruka_bot\__init__.py", line 10, in <module>
    from . import plugins  # noqa: F401
  File "E:\IDEAyes\BOT\CirnoBot-master\src\plugins\nonebot_plugin_haruka_bot\plugins\__init__.py", line 1, in <module>
    from . import (  # noqa: F401
  File "E:\IDEAyes\BOT\CirnoBot-master\src\plugins\nonebot_plugin_haruka_bot\plugins\at\__init__.py", line 1, in <module>
    from . import at_on, at_off  # noqa: F401
  File "E:\IDEAyes\BOT\CirnoBot-master\src\plugins\nonebot_plugin_haruka_bot\plugins\at\at_on.py", line 3, in <module>
    from nonebot.params import State
ImportError: cannot import name 'State' from 'nonebot.params' (E:\IDEAyes\BOT\CirnoBot-master\venv\lib\site-packages\nonebot\params.py)
```

**Comment by QwindF** [comment]
大概是以下的插件
```
nonebot_plugin_apscheduler
nonebot_plugin_currency_conversion
nonebot_plugin_cute_message
nonebot_plugin_database_connector
nonebot_plugin_mc_info
nonebot_plugin_mc_fun
nonebot_plugin_mc_cocdicer
nonebot_plugin_message_recorder
nonebot_plugin_archive
nonebot_plugin_what2eat
nonebot_plugin_tarot
nonebot_plugin_haruka_bot
```

依赖安装用的是pycharm的虚拟环境，自动完成安装的，请问是版本不对吗

**Comment by summerkirakira** [comment]
似乎是nonebot的版本问题

**Comment by QwindF** [comment]
请问该如何解决
