### ISSUE TITLE
帮助插件报错`

### ISSUE THREAD

**Issue by QwindF** [summerkirakira/CirnoBot#28]
```python
08-30 21:46:42 [ERROR] nonebot | Running Matcher(type='message', module=src.plugins.nonebot_plugin_help) failed.
Traceback (most recent call last):
  File "D:\BOT\CirnoBot\bot.py", line 28, in <module>
    nonebot.run()
  File "D:\BOT\CirnoBot\venv\Lib\site-packages\nonebot\__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "D:\BOT\CirnoBot\venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 199, in run
    uvicorn.run(
  File "D:\BOT\CirnoBot\venv\Lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "D:\BOT\CirnoBot\venv\Lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\BOT\CirnoBot\venv\Lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "D:\BOT\CirnoBot\venv\Lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\BOT\CirnoBot\venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 759, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\BOT\CirnoBot\venv\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 734, in simple_run
    await handler(
  File "D:\BOT\CirnoBot\venv\Lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\BOT\CirnoBot\src\plugins\nonebot_plugin_help\__init__.py", line 11, in _help_image
    await help_image.finish(Message(MessageSegment.image(await get_help())))
  File "D:\BOT\CirnoBot\src\plugins\nonebot_plugin_help\generate_help_image.py", line 110, in get_help
    return await make_plugins_image(new_list)
  File "D:\BOT\CirnoBot\src\plugins\nonebot_plugin_help\generate_help_image.py", line 75, in make_plugins_image
    plugin_image_list.append(make_single_plugin_image(plugins_list[i], i))
  File "D:\BOT\CirnoBot\src\plugins\nonebot_plugin_help\generate_help_image.py", line 28, in make_single_plugin_image
    if measure_length(message_preprocessed + ch, text_font) > description_box_width:
  File "D:\BOT\CirnoBot\src\plugins\nonebot_plugin_help\generate_help_image.py", line 14, in measure_length
    width, height = font.getsize(line)
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
```
![image](https://github.com/summerkirakira/CirnoBot/assets/87116340/8c7d8cf5-5757-4442-ad2a-6f59b2ce6952)

**Comment by QwindF** [comment]
已解决，是跟新了依赖导致的。
`pip install Pillow==9.5`
