### ISSUE TITLE
部分依赖找不到

### ISSUE THREAD

**Issue by alairack** [summerkirakira/CirnoBot#29]
我已经安装了requirements中的所有依赖，但还是提示包找不到

```
09-08 05:54:49 [SUCCESS] nonebot | NoneBot is initializing...
09-08 05:54:49 [INFO] nonebot | Current Env: prod
09-08 05:54:49 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
09-08 05:54:49 [ERROR] nonebot | Failed to import "nonebot_plugin_cute_message"
Traceback (most recent call last):
  File "bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "/home/ancares/CirnoBot/cirno_util.py", line 47, in load_plugins
    nonebot.load_plugin(plugin_name)
  File "/home/ancares/CirnoBot/venv/lib/python3.8/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "/home/ancares/CirnoBot/venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot_plugin_cute_message'
09-08 05:54:49 [ERROR] nonebot | Failed to import "nonebot_plugin_database_connector"
Traceback (most recent call last):
  File "bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "/home/ancares/CirnoBot/cirno_util.py", line 47, in load_plugins
    nonebot.load_plugin(plugin_name)
  File "/home/ancares/CirnoBot/venv/lib/python3.8/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "/home/ancares/CirnoBot/venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot_plugin_database_connector'
09-08 05:54:49 [ERROR] nonebot | Failed to import "nonebot_plugin_image_server"
Traceback (most recent call last):
  File "bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "/home/ancares/CirnoBot/cirno_util.py", line 47, in load_plugins
    nonebot.load_plugin(plugin_name)
  File "/home/ancares/CirnoBot/venv/lib/python3.8/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "/home/ancares/CirnoBot/venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot_plugin_image_server'
09-08 05:54:49 [ERROR] nonebot | Failed to import "nonebot_plugin_kaiheila_check"
Traceback (most recent call last):
  File "bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "/home/ancares/CirnoBot/cirno_util.py", line 47, in load_plugins
    nonebot.load_plugin(plugin_name)
  File "/home/ancares/CirnoBot/venv/lib/python3.8/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "/home/ancares/CirnoBot/venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot_plugin_kaiheila_check'
09-08 05:54:49 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_mc_info"
09-08 05:54:49 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_mc_fun"
09-08 05:54:49 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_permission"
09-08 05:54:49 [ERROR] nonebot | Failed to import "nonebot_plugin_archive"
Traceback (most recent call last):
  File "bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "/home/ancares/CirnoBot/cirno_util.py", line 47, in load_plugins
    nonebot.load_plugin(plugin_name)
  File "/home/ancares/CirnoBot/venv/lib/python3.8/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "/home/ancares/CirnoBot/venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot_plugin_archive'
09-08 05:54:49 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_help"
09-08 05:54:50 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
09-08 05:54:50 [ERROR] nonebot | Failed to import "nonebot_plugin_what2eat"
Traceback (most recent call last):
  File "bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "/home/ancares/CirnoBot/cirno_util.py", line 47, in load_plugins
    nonebot.load_plugin(plugin_name)
  File "/home/ancares/CirnoBot/venv/lib/python3.8/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "/home/ancares/CirnoBot/venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot_plugin_what2eat'
09-08 05:54:50 [ERROR] nonebot | Failed to import "nonebot_plugin_tarot"
Traceback (most recent call last):
  File "bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "/home/ancares/CirnoBot/cirno_util.py", line 47, in load_plugins
    nonebot.load_plugin(plugin_name)
  File "/home/ancares/CirnoBot/venv/lib/python3.8/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "/home/ancares/CirnoBot/venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot_plugin_tarot'
09-08 05:54:50 [ERROR] nonebot | Failed to import "nonebot_plugin_haruka_bot"
Traceback (most recent call last):
  File "bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "/home/ancares/CirnoBot/cirno_util.py", line 47, in load_plugins
    nonebot.load_plugin(plugin_name)
  File "/home/ancares/CirnoBot/venv/lib/python3.8/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "/home/ancares/CirnoBot/venv/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot_plugin_haruka_bot'
09-08 05:54:50 [SUCCESS] nonebot | Running NoneBot...
09-08 05:54:50 [INFO] uvicorn | Started server process [20472]
09-08 05:54:50 [INFO] uvicorn | Waiting for application startup.
09-08 05:54:50 [INFO] nonebot_plugin_apscheduler | Scheduler Started
```

**Comment by summerkirakira** [comment]
新版本许多无关功能已被移除，请照着仓库里的bot_config.yaml来配置加载的插件

**Comment by alairack** [comment]
@summerkirakira  感谢您的回复，但是我想用这些无关功能怎么办😂😂😂

**Comment by summerkirakira** [comment]
可以去[nonebot商店](https://nonebot.dev/store)或者[CirnoBot的历史提交记录](https://github.com/summerkirakira/CirnoBot/commits/master)里面找找找看

**Comment by alairack** [comment]
好的，感谢
