### ISSUE TITLE
cirnobot第一次启动时报错

### ISSUE THREAD

**Issue by MC-Nirvana** [summerkirakira/CirnoBot#30]
CirnoBot部署后第一次启动时报错，内容如下
PS E:\程序开发\Git仓库\CirnoBot> nb run
05-11 13:11:22 [SUCCESS] nonebot | NoneBot is initializing...
05-11 13:11:22 [INFO] nonebot | Current Env: prod
05-11 13:11:23 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
05-11 13:11:23 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_mc_info"
05-11 13:11:24 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_mc_fun"
05-11 13:11:24 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_permission"
05-11 13:11:24 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_help"
05-11 13:11:26 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
05-11 13:11:26 [ERROR] nonebot | Failed to import "nonebot_plugin_haruka_bot"
Traceback (most recent call last):
  File "E:\程序开发\Git仓库\CirnoBot\bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "E:\程序开发\Git仓库\CirnoBot\cirno_util.py", line 47, in load_plugins
    nonebot.load_plugin(plugin_name)
  File "C:\Program Files\Python311\Lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Program Files\Python311\Lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Program Files\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot_plugin_haruka_bot'
05-11 13:11:26 [SUCCESS] nonebot | Running NoneBot...
05-11 13:11:26 [INFO] logging | Started server process [10060]
05-11 13:11:26 [INFO] logging | Waiting for application startup.
05-11 13:11:26 [INFO] nonebot_plugin_apscheduler | Scheduler Started
05-11 13:11:27 [INFO] nonebot_plugin_gocqhttp | Startup complete, Web UI has served to http://127.0.0.1:4080/go-cqhttp/
05-11 13:11:27 [INFO] logging | Application startup complete.
05-11 13:11:27 [INFO] logging | Uvicorn running on http://127.0.0.1:4080 (Press CTRL+C to quit)
05-11 13:11:33 [INFO] logging | Shutting down
05-11 13:11:33 [INFO] logging | Finished server process [10060]
05-11 13:11:33 [INFO] nonebot_plugin_apscheduler | Scheduler Shutdown
05-11 13:11:33 [ERROR] logging | Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\starlette\routing.py", line 674, in lifespan
    await receive()
  File "C:\Program Files\Python311\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

操作系统：Microsoft Windows11 22H2（Build 22631.3527）
Python版本：3.11.4

**Comment by summerkirakira** [comment]
在bot_config.yaml中把nonebot_plugin_haruka_bot依赖去掉就好

________________________________
From: 涅 ***@***.***>
Sent: Saturday, May 11, 2024 6:16:40 AM
To: summerkirakira/CirnoBot ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [summerkirakira/CirnoBot] cirnobot第一次启动时报错 (Issue #30)


CirnoBot部署后第一次启动时报错，内容如下
PS E:\程序开发\Git仓库\CirnoBot> nb run
05-11 13:11:22 [SUCCESS] nonebot | NoneBot is initializing...
05-11 13:11:22 [INFO] nonebot | Current Env: prod
05-11 13:11:23 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
05-11 13:11:23 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_mc_info"
05-11 13:11:24 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_mc_fun"
05-11 13:11:24 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_permission"
05-11 13:11:24 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_help"
05-11 13:11:26 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
05-11 13:11:26 [ERROR] nonebot | Failed to import "nonebot_plugin_haruka_bot"
Traceback (most recent call last):
File "E:\程序开发\Git仓库\CirnoBot\bot.py", line 25, in
cirno_util.load_plugins()
File "E:\程序开发\Git仓库\CirnoBot\cirno_util.py", line 47, in load_plugins
nonebot.load_plugin(plugin_name)
File "C:\Program Files\Python311\Lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
return manager.load_plugin(module_path)

File "C:\Program Files\Python311\Lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
module = importlib.import_module(name)
File "C:\Program Files\Python311\Lib\importlib_init_.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1204, in _gcd_import
File "", line 1176, in _find_and_load
File "", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot_plugin_haruka_bot'
05-11 13:11:26 [SUCCESS] nonebot | Running NoneBot...
05-11 13:11:26 [INFO] logging | Started server process [10060]
05-11 13:11:26 [INFO] logging | Waiting for application startup.
05-11 13:11:26 [INFO] nonebot_plugin_apscheduler | Scheduler Started
05-11 13:11:27 [INFO] nonebot_plugin_gocqhttp | Startup complete, Web UI has served to http://127.0.0.1:4080/go-cqhttp/
05-11 13:11:27 [INFO] logging | Application startup complete.
05-11 13:11:27 [INFO] logging | Uvicorn running on http://127.0.0.1:4080 (Press CTRL+C to quit)
05-11 13:11:33 [INFO] logging | Shutting down
05-11 13:11:33 [INFO] logging | Finished server process [10060]
05-11 13:11:33 [INFO] nonebot_plugin_apscheduler | Scheduler Shutdown
05-11 13:11:33 [ERROR] logging | Traceback (most recent call last):
File "C:\Program Files\Python311\Lib\site-packages\starlette\routing.py", line 674, in lifespan
await receive()
File "C:\Program Files\Python311\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
return await self.receive_queue.get()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Program Files\Python311\Lib\asyncio\queues.py", line 158, in get
await getter
asyncio.exceptions.CancelledError

操作系统：Microsoft Windows11 22H2（Build 22631.3527）
Python版本：3.11.4

―

**Comment by xiao-k233** [comment]
小伙子你谁
