### ISSUE TITLE
Failed to import "nonebot_plugin_haruka_bot"

### ISSUE THREAD

**Issue by xiao-k233** [summerkirakira/CirnoBot#31]
```
07-02 10:17:24 [SUCCESS] nonebot | NoneBot is initializing...
07-02 10:17:24 [INFO] nonebot | Current Env: prod
07-02 10:17:24 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
07-02 10:17:24 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_mc_info"
07-02 10:17:24 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_mc_fun"
07-02 10:17:24 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_permission"
07-02 10:17:24 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_help"
07-02 10:17:25 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
07-02 10:17:25 [ERROR] nonebot | Failed to import "nonebot_plugin_haruka_bot"
Traceback (most recent call last):
  File "/root/CirnoBot/bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "/root/CirnoBot/cirno_util.py", line 47, in load_plugins
    nonebot.load_plugin(plugin_name)
  File "/root/CirnoBot/lib/python3.11/site-packages/nonebot/plugin/load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "/root/CirnoBot/lib/python3.11/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot_plugin_haruka_bot'
07-02 10:17:25 [SUCCESS] nonebot | Running NoneBot...
07-02 10:17:25 [INFO] logging | Started server process [2335]
07-02 10:17:25 [INFO] logging | Waiting for application startup.
07-02 10:17:25 [INFO] nonebot_plugin_apscheduler | Scheduler Started
```

**Comment by RushCN** [comment]
https://github.com/summerkirakira/CirnoBot/issues/30#issuecomment-2105619381
这里有解决办法。
