### ISSUE TITLE
'NoneType' object has no attribute 'connected'

### ISSUE THREAD

**Issue by Starry-Sky-World** [summerkirakira/CirnoBot#32]
Log：
```log
09-18 02:34:53 [SUCCESS] nonebot | OneBot V11 2295326064 | [message.group.normal]: Message -1905925508 from 1280993766@[群:734798675] ".mc"
09-18 02:34:53 [INFO] nonebot | Event will be handled by Matcher(type='message', module=src.plugins.nonebot_plugin_permission)
09-18 02:34:53 [INFO] nonebot | Matcher(type='message', module=src.plugins.nonebot_plugin_permission) running complete
09-18 02:34:53 [INFO] nonebot | Event will be handled by Matcher(type='message', module=src.plugins.nonebot_plugin_mc_fun.commands)
09-18 02:34:53 [INFO] nonebot | Matcher(type='message', module=src.plugins.nonebot_plugin_mc_fun.commands) running complete
09-18 02:34:53 [ERROR] nonebot | Running Matcher(type='message', module=src.plugins.nonebot_plugin_mc_fun.commands) failed.
Traceback (most recent call last):
  File "c:/Users/liu_q/Documents/Project/CirnoBot\bot.py", line 28, in <module>
    nonebot.run()
  File "C:\Users\liu_q\Documents\Project\CirnoBot\.venv\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\liu_q\Documents\Project\CirnoBot\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\liu_q\Documents\Project\CirnoBot\.venv\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\liu_q\Documents\Project\CirnoBot\.venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\liu_q\AppData\Local\Programs\Python\Python38\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\liu_q\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 595, in run_until_complete
    self.run_forever()
  File "C:\Users\liu_q\AppData\Local\Programs\Python\Python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\liu_q\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 563, in run_forever
    self._run_once()
  File "C:\Users\liu_q\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1844, in _run_once
    handle._run()
  File "C:\Users\liu_q\AppData\Local\Programs\Python\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\liu_q\Documents\Project\CirnoBot\.venv\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\liu_q\Documents\Project\CirnoBot\.venv\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\liu_q\Documents\Project\CirnoBot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\liu_q\Documents\Project\CirnoBot\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "C:\Users\liu_q\Documents\Project\CirnoBot\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "c:\Users\liu_q\Documents\Project\CirnoBot\src\plugins\nonebot_plugin_mc_fun\commands.py", line 55, in _server_status
    if not server.connected:
AttributeError: 'NoneType' object has no attribute 'connected'
```

请问如何解决

**Comment by summerkirakira** [comment]
确定服务端的servertap启动了吗，或者服务器地址填错了

**Comment by lonely-4** [comment]
> 确定服务端的servertap启动了吗，或者服务器地址填错了

对的，已启动，但是就是报这个错
