### ISSUE TITLE
feat: feel free to 闲聊

### ISSUE THREAD

**Issue by madoka-chann** [summerkirakira/CirnoBot#4]

**Comment by summerkirakira** [comment]
请拉取最新的代码并重建虚拟环境后重试哦

**Comment by summerkirakira** [comment]
请发送一下bot_config.yaml CirnoBot不会load_from_toml所以可能是你bot_config里加载了两遍

**Comment by madoka-chann** [comment]
我看一眼

**Comment by madoka-chann** [comment]
> 请发送一下bot_config.yaml CirnoBot不会load_from_toml所以可能是你bot_config里加载了两遍

？？？？？

![image](https://user-images.githubusercontent.com/57851695/154104876-9e14ad1b-321e-4b5d-a21f-4b24868ce580.png)

**Comment by summerkirakira** [comment]
> > 请发送一下bot_config.yaml CirnoBot不会load_from_toml所以可能是你bot_config里加载了两遍
> 
> ？？？？？
> 
> ![image](https://user-images.githubusercontent.com/57851695/154104876-9e14ad1b-321e-4b5d-a21f-4b24868ce580.png)

对啊，将haruka_bot内置在了bot里，重新拉取下代码吧

**Comment by summerkirakira** [comment]
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/56951617/154105705-e1e71c80-113d-404d-acc2-da936fa039fa.png">

**Comment by madoka-chann** [comment]
抱歉，我一直以为是hakura原来是haruka 😂

**Comment by summerkirakira** [comment]
![C7E2195FB4B46FD056195BE1AB73704A](https://user-images.githubusercontent.com/56951617/154106322-d9996d3b-3008-4f3c-961f-5bce347fc090.jpg)

**Comment by madoka-chann** [comment]
我复制下

**Comment by madoka-chann** [comment]
```
02-16 00:34:20 [ERROR] uvicorn | Traceback (most recent call last):
  File "/root/miniconda3/envs/cirno/lib/python3.10/site-packages/starlette/routing.py", line 621, in lifespan
    async with self.lifespan_context(app):
  File "/root/miniconda3/envs/cirno/lib/python3.10/site-packages/starlette/routing.py", line 518, in __aenter__
    await self._router.startup()
  File "/root/miniconda3/envs/cirno/lib/python3.10/site-packages/starlette/routing.py", line 598, in startup
    await handler()
  File "/home/ubuntu/BOTS/2 CirnoBot/./src/plugins/nonebot_plugin_haruka_bot/database/db.py", line 297, in init
    await db.init()
  File "/home/ubuntu/BOTS/2 CirnoBot/./src/plugins/nonebot_plugin_haruka_bot/database/db.py", line 31, in init
    from . import models  # noqa: F401
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/root/miniconda3/envs/cirno/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 163, in exec_module
    plugin = _new_plugin(self.name, module, self.manager)
  File "/root/miniconda3/envs/cirno/lib/python3.10/site-packages/nonebot/plugin/plugin.py", line 97, in _new_plugin
    raise RuntimeError("Plugin already exists! Check your plugin name.")
RuntimeError: Plugin already exists! Check your plugin name.
```

**Comment by summerkirakira** [comment]
把原来的那个haruka bot删除了吗

**Comment by madoka-chann** [comment]
删除了

**Comment by madoka-chann** [comment]
pip list下不存在

**Comment by madoka-chann** [comment]
大概是我http-core没有删除？你在requirements.txt里删掉了

**Comment by madoka-chann** [comment]
而且我是新创建了一个python3.10.0的虚拟环境安装的

**Comment by summerkirakira** [comment]
请发送一下bot_config的配置，敏感信息删掉就可以了

**Comment by madoka-chann** [comment]
```
bot_enabled: true # 总开关

host: 127.0.0.1 # 当gocq在本地运行时请不要改动这两项
port: 32156

#gocq_accounts:
#  - uin: 账号
#    password: 密码

# 手动配置登录的QQ账号，可以选择多个，请注意启用nonebot_plugin_gocqhttp

gocq_download_domain: download.fastgit.org # 如遇到下载出错或海外服务器请使用github.com哦

superuser:
  - '1691914478' # 主人账号
  - '543077304' # 可添加多个

plugins_config: # 包含基础设置，精确控制请移步插件文件夹

  nonebot_plugin_apscheduler: # 定时任务插件，多插件依赖，请勿关闭
    enabled: true

  nonebot_plugin_currency_conversion: # 汇率转换
    enabled: true # 如功能失效，请去 src/plugins/nonebot_plugin_currency_conversion/config.yaml 配置密钥

  nonebot_plugin_cute_message: # 正则匹配图文回复以及戳一戳回复
    enabled: true # 请去 src/plugins/nonebot_plugin_cute_message/config.py 自定回复

  nonebot_plugin_database_connector: # 数据库连接件，词条及消息记录模块依赖，请勿关闭（如果你不知道自己在做什么的话）>_<
    enabled: true

  nonebot_plugin_image_server: # 图片缓存服务器，词条模块依赖，用于缓存词条图片，关闭后词条无法录入图片信息 QAQ
    enabled: true
    image_server_url: localhost:4500 # 图片存储地址，用于gocq获取图片。如果你的gocq和bot在同一位置，请不要更改此选项（别乱改就完事了 上面那个也是）

  nonebot_plugin_kaiheila_check: # 开黑啦信息查询
    enabled: true # 请去 src/plugins/nonebot_plugin_kaiheila_check/config.yaml 配置密钥

  nonebot_plugin_mc_info: # MC服务器连接器，所有mc功能的基础
    enabled: true # 请去 src/plugins/nonebot_plugin_mc_info/config.yaml 配置密钥

  nonebot_plugin_mc_fun: # 提供MC服务器管理等一系列功能（冷知识：这里的fun是function的缩写）
    enabled: true # 请去 src/plugins/nonebot_plugin_mc_fun/config.yaml 配置密钥，对啦，不要惊讶，如果不配置上面那个mc_info, 这会是个空文件

  nonebot_plugin_mc_cocdicer: # MC 跑团插件（注意，是mc哦）
    enabled: true # 其实这个选项并没有任何用处，但还是加上去惹，很有仪式感，不是么

  nonebot_plugin_message_recorder: # 消息记录器，需要配置监控的群才会生效哦
    enabled: true # 请去 src/plugins/nonebot_message_recorder/config.yaml 配置

  nonebot_plugin_permission: # 一个简单的权限管理器
    enabled: true # 请去 src/plugins/nonebot_plugin_permission/config.yaml 配置

  nonebot_plugin_archive: # 词条系统
    enabled: true # 是否开启
    only_admin_can_edit: false # 是否仅允许管理员编辑

  nonebot_plugin_help: # 帮助系统
    enabled: true # 是否开启

  nonebot_plugin_gocqhttp: # 来自mix佬，在nonebot进程中运行gocq!(无需独立启动来运行QQ）
    enabled: false # 如果你有将bot和nonebot放在不同服务器的需求，请禁用此项（别忘了把最上面的host改成0.0.0.0哦）

  nonebot_plugin_what2eat: # 今天吃什么！配置请参考https://github.com/KafCoppelia/nonebot_plugin_what2eat
    enabled: true

  nonebot_plugin_tarot: # 塔罗牌！配置请参考https://github.com/KafCoppelia/nonebot_plugin_tarot
    enabled: true

  nonebot_plugin_haruka_bot: # b站主播开播自动推送！配置请参考https://github.com/SK-415/HarukaBot
    enabled: true


command_start:
  - .

haruka_to_me: true

nickname:
  - 小九
  - 琪露诺

```

**Comment by summerkirakira** [comment]
重新拉取代码吧，而且nb 在Python 3.10下可能会有兼容性问题

**Comment by madoka-chann** [comment]
那我先close掉了，晚安 

## 话说我有一整套你头像的图片哎，当初专门去pixiv上找的
![FA}WV7D2(}WU51H7P_%203A](https://user-images.githubusercontent.com/57851695/154108453-5bab3856-1363-4d04-be61-59666c67e37b.jpg)
![AJ~~17X)PN%2K9M)F4) 0~X](https://user-images.githubusercontent.com/57851695/154108512-a994334f-4903-4450-bf9a-e3693a31abc2.jpg)

**Comment by summerkirakira** [comment]
![1c7b1c950a7b0208906962fb3fd9f2d3562cc882.jpg](https://user-images.githubusercontent.com/56951617/154108741-976f69b8-2a85-4ccf-b96f-a2aab722c33f.jpg)

**Comment by summerkirakira** [comment]
> 那我先close掉了，晚安 
> 
> ## 话说我有一整套你头像的图片哎，当初专门去pixiv上找的
> ![FA}WV7D2(}WU51H7P_%203A](https://user-images.githubusercontent.com/57851695/154108453-5bab3856-1363-4d04-be61-59666c67e37b.jpg)
> ![AJ~~17X)PN%2K9M)F4) 0~X](https://user-images.githubusercontent.com/57851695/154108512-a994334f-4903-4450-bf9a-e3693a31abc2.jpg)
> 
> 
> 
> 

小圆cosplay.jpg
![383db1345982b2b77c2fbedc6cadcbef77099bf4.jpg](https://user-images.githubusercontent.com/56951617/154109498-27bc2a67-6868-4c2e-8eb2-673de68fdaa8.jpg)

**Comment by madoka-chann** [comment]
> 

下周要和同学出圆焰cos，好消息是：我是小圆，她更喜欢小焰一点

**Comment by summerkirakira** [comment]
好诶，是弱气攻

**Comment by madoka-chann** [comment]
> 好诶，是弱气攻

![85`KX}V3 _ 7~9@QOR1RJF5](https://user-images.githubusercontent.com/57851695/154111591-6c57815b-9ba8-4d65-9465-efeac3915da3.png)

**Comment by madoka-chann** [comment]
溜了溜了，有啥建议改天再来

**Comment by summerkirakira** [comment]
如果有off topic的话建议加群（）
