### ISSUE TITLE
[ERROR] Failed to import "src.plugins.nonebot_plugin_haruka_bot"

### ISSUE THREAD

**Issue by madoka-chann** [summerkirakira/CirnoBot#5]
我在conda里装了一个py3.8.3，又拉了一遍更新，结果：

```
02-16 01:11:30 [SUCCESS] nonebot | NoneBot is initializing...
02-16 01:11:30 [INFO] nonebot | Current Env: prod
02-16 01:11:30 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_apscheduler"
02-16 01:11:30 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_currency_conversion"
02-16 01:11:30 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_cute_message"
02-16 01:11:30 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_database_connector"
02-16 01:11:30 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_image_server"
02-16 01:11:30 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_kaiheila_check"
02-16 01:11:30 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_mc_info"
02-16 01:11:31 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_mc_fun"
02-16 01:11:31 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_mc_cocdicer"
02-16 01:11:31 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_message_recorder"
02-16 01:11:32 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_permission"
02-16 01:11:32 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_archive"
02-16 01:11:32 [SUCCESS] nonebot | Succeeded to import "src.plugins.nonebot_plugin_help"
/root/miniconda3/envs/mc/lib/python3.8/site-packages/apscheduler/util.py:95: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  if obj.zone == 'local':
02-16 01:11:32 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_what2eat"
02-16 01:11:32 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_tarot"
02-16 01:11:33 [ERROR] nonebot | Failed to import "src.plugins.nonebot_plugin_haruka_bot"
Traceback (most recent call last):
  File "/root/miniconda3/envs/mc/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/mc/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/mc/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/mc/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/mc/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/mc/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/mc/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/root/miniconda3/envs/mc/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 19, in run_bot
    module = importlib.import_module(module_name)
  File "/root/miniconda3/envs/mc/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./bot.py", line 25, in <module>
    cirno_util.load_plugins()
  File "./cirno_util.py", line 45, in load_plugins
    nonebot.load_plugin(f"src.plugins.{plugin_name}")
  File "/root/miniconda3/envs/mc/lib/python3.8/site-packages/nonebot/plugin/load.py", line 30, in load_plugin
    return manager.load_plugin(module_path)
> File "/root/miniconda3/envs/mc/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 92, in load_plugin
    module = importlib.import_module(name)
  File "/root/miniconda3/envs/mc/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/root/miniconda3/envs/mc/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 181, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./src/plugins/nonebot_plugin_haruka_bot/__init__.py", line 10, in <module>
    from . import plugins  # noqa: F401
  File "./src/plugins/nonebot_plugin_haruka_bot/plugins/__init__.py", line 1, in <module>
    from . import (  # noqa: F401
  File "./src/plugins/nonebot_plugin_haruka_bot/plugins/at/__init__.py", line 1, in <module>
    from . import at_on, at_off  # noqa: F401
  File "./src/plugins/nonebot_plugin_haruka_bot/plugins/at/at_on.py", line 9, in <module>
    from ...database import DB
  File "./src/plugins/nonebot_plugin_haruka_bot/database/__init__.py", line 1, in <module>
    from .db import DB  # noqa: F401
  File "./src/plugins/nonebot_plugin_haruka_bot/database/db.py", line 304, in <module>
    get_driver().on_shutdown(Tortoise.close_connections)
AttributeError: type object 'Tortoise' has no attribute 'close_connections'
02-16 01:11:33 [SUCCESS] nonebot | Running NoneBot...
02-16 01:11:33 [INFO] uvicorn | Started server process [357544]
02-16 01:11:33 [INFO] uvicorn | Waiting for application startup.
/root/miniconda3/envs/mc/lib/python3.8/site-packages/apscheduler/triggers/cron/__init__.py:159: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return self.timezone.localize(datetime(**values))
02-16 01:11:33 [INFO] src | Scheduler Started
02-16 01:11:33 [WARNING] src | 端口被占用，可能原因为图片存储服务器未正常退出，不再重复创建
02-16 01:11:33 [INFO] src | 正在检查 Chromium 更新
02-16 01:11:33 [ERROR] uvicorn | Traceback (most recent call last):
  File "/root/miniconda3/envs/mc/lib/python3.8/site-packages/starlette/routing.py", line 621, in lifespan
    async with self.lifespan_context(app):
  File "/root/miniconda3/envs/mc/lib/python3.8/site-packages/starlette/routing.py", line 518, in __aenter__
    await self._router.startup()
  File "/root/miniconda3/envs/mc/lib/python3.8/site-packages/starlette/routing.py", line 598, in startup
    await handler()
  File "./src/plugins/nonebot_plugin_haruka_bot/database/db.py", line 297, in init
    await db.init()
  File "./src/plugins/nonebot_plugin_haruka_bot/database/db.py", line 31, in init
    from . import models  # noqa: F401
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/root/miniconda3/envs/mc/lib/python3.8/site-packages/nonebot/plugin/manager.py", line 163, in exec_module
    plugin = _new_plugin(self.name, module, self.manager)
  File "/root/miniconda3/envs/mc/lib/python3.8/site-packages/nonebot/plugin/plugin.py", line 97, in _new_plugin
    raise RuntimeError("Plugin already exists! Check your plugin name.")
RuntimeError: Plugin already exists! Check your plugin name.

02-16 01:11:33 [ERROR] uvicorn | Application startup failed. Exiting.
(mc) root@VM-12-12-ubuntu:/home/ubuntu/BOTS/CirnoBot-master (3)/CirnoBot-master# 
```

**Comment by summerkirakira** [comment]
我测试下

**Comment by madoka-chann** [comment]
> 我测试下

log

**Comment by madoka-chann** [comment]
我也测试了一下，把haruka给false了，然后不影响正常启动和连接，但是bot无法处理信息了，发送指令没有反应：（是私聊，群聊暂时风控了）
![image](https://user-images.githubusercontent.com/57851695/154115359-25449322-3330-4158-9c93-19c16fd31200.png)

**Comment by summerkirakira** [comment]
> 我也测试了一下，把haruka给false了，然后不影响正常启动和连接，但是bot无法处理信息了，发送指令没有反应：（是私聊，群聊暂时风控了）
> ![image](https://user-images.githubusercontent.com/57851695/154115359-25449322-3330-4158-9c93-19c16fd31200.png)
> 

CirnoBot 绝大多数功能都是针对群聊做的，私聊没有反应是正常的

**Comment by madoka-chann** [comment]
在你更haruka依赖之前，我删了内置的词条插件、cute message、harukabot、图片存储数据库，但是不影响bot对指令的反应，

**Comment by summerkirakira** [comment]
但是塔罗牌这种应该不影响吧，可能是风控

**Comment by madoka-chann** [comment]
> > 我也测试了一下，把haruka给false了，然后不影响正常启动和连接，但是bot无法处理信息了，发送指令没有反应：（是私聊，群聊暂时风控了）
> > ![image](https://user-images.githubusercontent.com/57851695/154115359-25449322-3330-4158-9c93-19c16fd31200.png)
> 
> CirnoBot 绝大多数功能都是针对群聊做的，私聊没有反应是正常的

我之前私聊还会回复.帮助，现在也不会回复了

**Comment by madoka-chann** [comment]
突然可以了？

**Comment by madoka-chann** [comment]
我试试其他的

**Comment by summerkirakira** [comment]
应该是风控问题，有时候gocq也不知道自己有没有发出去

**Comment by madoka-chann** [comment]
> 应该是风控问题，有时候gocq也不知道自己有没有发出去

那报错的原因找到了嘛

**Comment by madoka-chann** [comment]
shall we sleep, bye, night night, code tomorrow...uwu

**Comment by summerkirakira** [comment]
> > 应该是风控问题，有时候gocq也不知道自己有没有发出去
> 
> 那报错的原因找到了嘛

稍等

**Comment by summerkirakira** [comment]
![Screenshot_20220215-173701.jpg](https://user-images.githubusercontent.com/56951617/154117684-97ea0072-d133-48b9-a745-101da33f33af.jpg)
加载完全正常呀，可能是你bot_config配置错误了

**Comment by summerkirakira** [comment]
系统也是Ubuntu

**Comment by madoka-chann** [comment]
不会吧不会吧，我bot_config就配置过主人，然后改了下port，其他完全没动

**Comment by summerkirakira** [comment]
> 不会吧不会吧，我bot_config就配置过主人，然后改了下port，其他完全没动

重新clone仓库吧

**Comment by madoka-chann** [comment]
额，你在上一个issue表示我配置文件没问题，让我再换个低点的py并且重新clone，照做了，配置文件也完全没有变（）我明天再看看吧

**Comment by summerkirakira** [comment]
嗯嗯，有什么问题随时问就行（

**Comment by madoka-chann** [comment]
你的py版本是

**Comment by summerkirakira** [comment]
和python版本关系不大3.8、3.9都能正常安装

**Comment by summerkirakira** [comment]
经测试playwright在3.10下似乎有兼容性问题？请最好降级到Python 3.8或者3.9。

**Comment by FuYon** [comment]
> 

早就降级过了
